# Generated by Django 3.0.7 on 2020-12-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin_table',
        ),
        migrations.RenameModel(
            old_name='req_recived_blood',
            new_name='req_received_blood',
        ),
        migrations.RenameField(
            model_name='req_received_blood',
            old_name='RECIVED_AMOUNT',
            new_name='RECEIVED_AMOUNT',
        ),
        migrations.AlterField(
            model_name='donor',
            name='WANT_TO_DONATE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='admin_table',
            table='admin_table',
        ),
    ]
