# Generated by Django 3.0.7 on 2020-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0003_auto_20201228_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_table',
            name='PHONE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='PHONE',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='PHONENO',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='PHONENO',
            field=models.CharField(max_length=50),
        ),
    ]
