# Generated by Django 3.0.7 on 2020-12-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0005_hospital_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='H_ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='EMP_ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
