# Generated by Django 3.0.7 on 2020-12-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0006_auto_20201228_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='AADHARNO',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='req_received_blood',
            name='H_ID',
            field=models.CharField(max_length=50),
        ),
    ]
