# Generated by Django 3.0.7 on 2020-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0009_auto_20201228_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ADDRESS',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='PIN',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
